"""Type stubs for the ``spire`` Python package (SPIRE HEP toolkit)."""

from __future__ import annotations

from typing import Optional, Sequence

import numpy as np
import numpy.typing as npt

__version__: str

# ── Model ─────────────────────────────────────────────────────────────

class Field:
    """A quantum field definition from a theoretical model."""

    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def symbol(self) -> str: ...
    @property
    def mass(self) -> float: ...
    @property
    def width(self) -> float: ...
    @property
    def spin(self) -> float: ...
    @property
    def electric_charge(self) -> float: ...
    @property
    def baryon_number(self) -> float: ...
    @property
    def lepton_numbers(self) -> tuple[int, int, int]: ...
    @property
    def color(self) -> str: ...
    @property
    def interactions(self) -> list[str]: ...
    def to_json(self) -> str: ...
    def _repr_html_(self) -> str: ...

class Particle:
    """An on-shell or off-shell excitation of a Field."""

    @property
    def field(self) -> Field: ...
    @property
    def is_on_shell(self) -> bool: ...
    @property
    def is_anti(self) -> bool: ...
    @property
    def helicity(self) -> Optional[str]: ...
    @property
    def chirality(self) -> Optional[str]: ...
    def _repr_html_(self) -> str: ...

class Model:
    """
    A theoretical model (e.g. the Standard Model).

    Use ``Model.standard_model()`` to load the built-in SM, or
    ``Model.from_toml(...)`` for custom models.
    """

    @staticmethod
    def standard_model() -> Model: ...
    @staticmethod
    def from_toml(
        particles_toml: str,
        vertices_toml: str,
        name: str = "Custom Model",
    ) -> Model: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def num_fields(self) -> int: ...
    @property
    def num_vertices(self) -> int: ...
    @property
    def fields(self) -> list[Field]: ...
    def get_field(self, field_id: str) -> Field: ...
    def to_json(self) -> str: ...
    def _repr_html_(self) -> str: ...

# ── Reaction ──────────────────────────────────────────────────────────

class Reaction:
    """A scattering or decay process: initial → final state."""

    @staticmethod
    def create(
        model: Model,
        initial: list[str],
        final_state: list[str],
        cms_energy: Optional[float] = None,
    ) -> Reaction: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def violations(self) -> list[str]: ...
    @property
    def interaction_types(self) -> list[str]: ...
    @property
    def mediating_bosons(self) -> list[Particle]: ...
    @property
    def num_initial(self) -> int: ...
    @property
    def num_final(self) -> int: ...
    def to_json(self) -> str: ...
    def _repr_html_(self) -> str: ...

# ── Diagrams ──────────────────────────────────────────────────────────

class DiagramSet:
    """A set of Feynman diagrams generated for a reaction."""

    @staticmethod
    def generate(
        reaction: Reaction,
        model: Model,
        max_loop_order: int = 0,
    ) -> DiagramSet: ...
    @property
    def count(self) -> int: ...
    def to_json(self) -> str: ...
    def __len__(self) -> int: ...
    def _repr_html_(self) -> str: ...

# ── Amplitude ─────────────────────────────────────────────────────────

class AmplitudeResult:
    """Symbolic amplitude expression for a Feynman diagram."""

    expression: str
    couplings: list[str]
    momenta_labels: list[str]

    @staticmethod
    def from_diagram_json(diagram_json: str) -> AmplitudeResult: ...
    def to_json(self) -> str: ...
    def _repr_html_(self) -> str: ...

# ── Cross-Sections ────────────────────────────────────────────────────

class CrossSectionResult:
    """Result of a partonic cross-section calculation."""

    @staticmethod
    def calculate(
        cms_energy: float,
        final_masses: list[float],
        num_events: int,
    ) -> CrossSectionResult: ...
    @property
    def cross_section(self) -> float: ...
    @property
    def uncertainty(self) -> float: ...
    @property
    def cross_section_pb(self) -> float: ...
    @property
    def uncertainty_pb(self) -> float: ...
    @property
    def events_evaluated(self) -> int: ...
    @property
    def relative_error(self) -> float: ...
    @property
    def cms_energy(self) -> float: ...
    def _repr_html_(self) -> str: ...

class HadronicCrossSectionResult:
    """Result of a hadronic (PDF-convoluted) cross-section calculation."""

    @staticmethod
    def calculate(
        beam_energy_sq: float,
        final_masses: list[float],
        num_events: int,
    ) -> HadronicCrossSectionResult: ...
    @property
    def cross_section(self) -> float: ...
    @property
    def uncertainty(self) -> float: ...
    @property
    def cross_section_pb(self) -> float: ...
    @property
    def uncertainty_pb(self) -> float: ...
    @property
    def events_evaluated(self) -> int: ...
    @property
    def relative_error(self) -> float: ...
    @property
    def beam_energy_sq(self) -> float: ...
    @property
    def pdf_name(self) -> str: ...
    @property
    def beam_description(self) -> str: ...
    def _repr_html_(self) -> str: ...

# ── Events ────────────────────────────────────────────────────────────

class EventGenerator:
    """
    Phase-space event generator backed by the RAMBO algorithm.

    Generates Lorentz-invariant N-body phase-space points and returns
    them as zero-copy NumPy arrays.
    """

    def __init__(
        self,
        cms_energy: float,
        final_masses: list[float],
        seed: Optional[int] = None,
    ) -> None: ...
    @property
    def cms_energy(self) -> float: ...
    @property
    def final_masses(self) -> list[float]: ...
    @property
    def num_particles(self) -> int: ...
    def generate(
        self, num_events: int
    ) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]:
        """
        Generate events as structured NumPy arrays.

        Returns
        -------
        momenta : ndarray, shape (num_events, num_particles, 4)
        weights : ndarray, shape (num_events,)
        """
        ...
    def generate_flat(self, num_events: int) -> npt.NDArray[np.float64]:
        """
        Generate events as a flat 2-D array.

        Returns
        -------
        events : ndarray, shape (num_events, num_particles * 4)
        """
        ...
    def _repr_html_(self) -> str: ...

# ── Decay ─────────────────────────────────────────────────────────────

class DecayChannel:
    """A single decay channel with partial width and branching ratio."""

    @property
    def final_state(self) -> list[str]: ...
    @property
    def final_state_names(self) -> list[str]: ...
    @property
    def partial_width(self) -> float: ...
    @property
    def branching_ratio(self) -> float: ...
    @property
    def vertex_id(self) -> str: ...

class DecayTable:
    """Complete decay table for a parent particle."""

    @staticmethod
    def calculate(model: Model, particle_id: str) -> DecayTable: ...
    @property
    def parent_id(self) -> str: ...
    @property
    def parent_name(self) -> str: ...
    @property
    def parent_mass(self) -> float: ...
    @property
    def total_width(self) -> float: ...
    @property
    def lifetime_seconds(self) -> float: ...
    @property
    def num_channels(self) -> int: ...
    @property
    def channels(self) -> list[DecayChannel]: ...
    def to_slha(self, pdg_code: int) -> str: ...
    def __len__(self) -> int: ...
    def _repr_html_(self) -> str: ...

# ── Kinematics ────────────────────────────────────────────────────────

def calculate_threshold(
    final_masses: list[float],
    target_mass: Optional[float] = None,
) -> dict[str, object]:
    """
    Calculate threshold energy for a set of final-state masses.

    Returns a dict with keys: ``threshold_energy``, ``lab_energy``, ``final_masses``.
    """
    ...

def is_kinematically_allowed(cms_energy: float, final_masses: list[float]) -> bool:
    """Check whether a process is kinematically allowed at a given CM energy."""
    ...
