//! # GPU Integrator - Hardware-Accelerated Monte Carlo via WebGPU
//!
//! This module provides a GPU-accelerated Monte Carlo integrator that
//! evaluates squared amplitudes $|\mathcal{M}|^2$ on the GPU using
//! compute shaders generated by the [`WgslCompiler`].
//!
//! ## Architecture
//!
//! ```text
//! CPU (Host)                          GPU (Device)
//! ┌──────────────────┐               ┌──────────────────┐
//! │ RamboGenerator   │──momenta───►  │ momenta buffer   │
//! │ (phase space)    │               │ (storage, read)  │
//! └──────────────────┘               ├──────────────────┤
//!                                    │ WGSL shader      │
//!                                    │ |M|² evaluation  │
//!                                    ├──────────────────┤
//! ┌──────────────────┐  ◄─results──  │ results buffer   │
//! │ CPU reduction    │               │ (storage, r/w)   │
//! │ Σ, σ², stats     │               └──────────────────┘
//! └──────────────────┘
//! ```
//!
//! 1. Phase-space points are generated on the CPU (RAMBO).
//! 2. Four-momenta are uploaded to a GPU storage buffer.
//! 3. A compute shader evaluates $|\mathcal{M}|^2$ for all events in
//!    parallel (one invocation per event).
//! 4. Results are read back to the CPU for statistical reduction
//!    (cross-section estimate, variance, error).
//!
//! ## Feature Gate
//!
//! This module is only compiled when the `gpu` feature is enabled:
//! ```toml
//! [dependencies]
//! spire-kernel = { path = "...", features = ["gpu"] }
//! ```
//!
//! [`WgslCompiler`]: crate::algebra::wgsl_compiler::WgslCompiler

use bytemuck::{Pod, Zeroable};
use wgpu::util::DeviceExt;

use crate::integration::IntegrationResult;
use crate::kinematics::{PhaseSpaceGenerator, PhaseSpacePoint};
use crate::SpireResult;

// ===========================================================================
// GPU Uniform Parameters
// ===========================================================================

/// Uniform buffer layout matching the `Params` struct in the WGSL shader.
///
/// This is the minimal set of parameters common to every shader. The
/// WGSL compiler may add additional fields for coupling constants and
/// masses - those are appended after `n_events` in the actual GPU buffer
/// and must be set separately.
#[repr(C)]
#[derive(Debug, Clone, Copy, Pod, Zeroable)]
pub struct GpuParams {
    /// Number of events in this dispatch.
    pub n_events: u32,
    /// Padding to ensure 16-byte alignment.
    pub _pad: [u32; 3],
}

// ===========================================================================
// GPU Integrator
// ===========================================================================

/// A hardware-accelerated Monte Carlo integrator using WebGPU compute
/// shaders.
///
/// # Lifecycle
///
/// 1. Call [`GpuIntegrator::new`] to create a device and queue.
/// 2. Call [`GpuIntegrator::integrate`] with a WGSL shader, a
///    phase-space generator, and integration parameters.
/// 3. The integrator uploads momenta, dispatches the shader, reads back
///    $|\mathcal{M}|^2$ values, and performs the statistical reduction on
///    the CPU.
pub struct GpuIntegrator {
    /// The wgpu device handle.
    device: wgpu::Device,
    /// The command queue for GPU submissions.
    queue: wgpu::Queue,
    /// Human-readable description of the GPU adapter.
    pub adapter_info: String,
}

impl GpuIntegrator {
    /// Create a new GPU integrator by requesting the best available
    /// adapter.
    ///
    /// This blocks on adapter and device creation using `pollster`.
    /// Returns `None` if no suitable GPU adapter is found.
    pub fn new() -> Option<Self> {
        pollster::block_on(Self::new_async())
    }

    /// Async constructor for environments with an existing async runtime.
    async fn new_async() -> Option<Self> {
        let instance = wgpu::Instance::new(&wgpu::InstanceDescriptor {
            backends: wgpu::Backends::all(),
            ..Default::default()
        });

        let adapter = instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::HighPerformance,
                force_fallback_adapter: false,
                compatible_surface: None,
            })
            .await?;

        let info = adapter.get_info();
        let adapter_info = format!(
            "{} ({:?}, {:?})",
            info.name, info.backend, info.device_type
        );

        let (device, queue) = adapter
            .request_device(
                &wgpu::DeviceDescriptor {
                    label: Some("SPIRE GPU Integrator"),
                    required_features: wgpu::Features::empty(),
                    required_limits: wgpu::Limits::default(),
                    memory_hints: wgpu::MemoryHints::Performance,
                },
                None,
            )
            .await
            .ok()?;

        Some(Self {
            device,
            queue,
            adapter_info,
        })
    }

    /// Run a GPU-accelerated Monte Carlo integration.
    ///
    /// # Arguments
    ///
    /// * `shader_source` - Complete WGSL source code generated by the
    ///   [`WgslCompiler`]. Must contain the `main` entry point.
    /// * `generator` - A phase-space generator for producing momenta on
    ///   the CPU.
    /// * `cms_energy` - Centre-of-mass energy $\sqrt{s}$ in GeV.
    /// * `final_masses` - Rest masses of final-state particles (GeV).
    /// * `n_momenta_per_event` - Number of four-momenta per event
    ///   (initial + final state particles).
    /// * `num_events` - Total number of Monte Carlo events.
    /// * `params_data` - Raw bytes for the uniform `Params` buffer
    ///   (must match the shader's `Params` struct layout exactly).
    ///
    /// # Returns
    ///
    /// An [`IntegrationResult`] with the cross-section estimate and
    /// statistical uncertainty.
    #[allow(clippy::too_many_arguments)]
    pub fn integrate(
        &self,
        shader_source: &str,
        generator: &mut dyn PhaseSpaceGenerator,
        cms_energy: f64,
        final_masses: &[f64],
        n_momenta_per_event: usize,
        num_events: usize,
        params_data: &[u8],
    ) -> SpireResult<IntegrationResult> {
        // -----------------------------------------------------------------
        // Step 1: Generate phase-space points on the CPU
        // -----------------------------------------------------------------
        let mut ps_points: Vec<PhaseSpacePoint> = Vec::with_capacity(num_events);
        for _ in 0..num_events {
            match generator.generate_event(cms_energy, final_masses) {
                Ok(point) => ps_points.push(point),
                Err(_) => continue,
            }
        }

        let n_valid = ps_points.len();
        if n_valid == 0 {
            return Ok(IntegrationResult {
                value: 0.0,
                error: 0.0,
                events_evaluated: 0,
                efficiency: 0.0,
                relative_error: 0.0,
            });
        }

        // -----------------------------------------------------------------
        // Step 2: Pack momenta into a flat f32 buffer
        // -----------------------------------------------------------------
        // Layout: [event0_p0(E,px,py,pz), event0_p1(E,px,py,pz), ...,
        //          event1_p0, ...]
        let buffer_len = n_valid * n_momenta_per_event * 4;
        let mut momenta_f32: Vec<f32> = vec![0.0; buffer_len];

        for (ev_idx, point) in ps_points.iter().enumerate() {
            for (p_idx, momentum) in point.momenta.iter().enumerate() {
                if p_idx >= n_momenta_per_event {
                    break;
                }
                let base = (ev_idx * n_momenta_per_event + p_idx) * 4;
                let comps = momentum.components();
                for (c, &val) in momenta_f32[base..base + comps.len().min(4)]
                    .iter_mut()
                    .zip(comps.iter())
                {
                    *c = val as f32;
                }
            }
        }

        // -----------------------------------------------------------------
        // Step 3: Create GPU buffers
        // -----------------------------------------------------------------
        let momenta_buffer = self
            .device
            .create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("momenta"),
                contents: bytemuck::cast_slice(&momenta_f32),
                usage: wgpu::BufferUsages::STORAGE,
            });

        let results_buffer = self.device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("results"),
            size: (n_valid * std::mem::size_of::<f32>()) as u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
            mapped_at_creation: false,
        });

        let staging_buffer = self.device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("staging"),
            size: (n_valid * std::mem::size_of::<f32>()) as u64,
            usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let params_buffer = self
            .device
            .create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("params"),
                contents: params_data,
                usage: wgpu::BufferUsages::UNIFORM,
            });

        // -----------------------------------------------------------------
        // Step 4: Create compute pipeline
        // -----------------------------------------------------------------
        let shader_module = self
            .device
            .create_shader_module(wgpu::ShaderModuleDescriptor {
                label: Some("amplitude_shader"),
                source: wgpu::ShaderSource::Wgsl(shader_source.into()),
            });

        let bind_group_layout =
            self.device
                .create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                    label: Some("integrator_bgl"),
                    entries: &[
                        // @binding(0) momenta (storage, read)
                        wgpu::BindGroupLayoutEntry {
                            binding: 0,
                            visibility: wgpu::ShaderStages::COMPUTE,
                            ty: wgpu::BindingType::Buffer {
                                ty: wgpu::BufferBindingType::Storage { read_only: true },
                                has_dynamic_offset: false,
                                min_binding_size: None,
                            },
                            count: None,
                        },
                        // @binding(1) results (storage, read_write)
                        wgpu::BindGroupLayoutEntry {
                            binding: 1,
                            visibility: wgpu::ShaderStages::COMPUTE,
                            ty: wgpu::BindingType::Buffer {
                                ty: wgpu::BufferBindingType::Storage { read_only: false },
                                has_dynamic_offset: false,
                                min_binding_size: None,
                            },
                            count: None,
                        },
                        // @binding(2) params (uniform)
                        wgpu::BindGroupLayoutEntry {
                            binding: 2,
                            visibility: wgpu::ShaderStages::COMPUTE,
                            ty: wgpu::BindingType::Buffer {
                                ty: wgpu::BufferBindingType::Uniform,
                                has_dynamic_offset: false,
                                min_binding_size: None,
                            },
                            count: None,
                        },
                    ],
                });

        let pipeline_layout =
            self.device
                .create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                    label: Some("integrator_pipeline_layout"),
                    bind_group_layouts: &[&bind_group_layout],
                    push_constant_ranges: &[],
                });

        let pipeline = self
            .device
            .create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                label: Some("integrator_pipeline"),
                layout: Some(&pipeline_layout),
                module: &shader_module,
                entry_point: Some("main"),
                compilation_options: Default::default(),
                cache: None,
            });

        let bind_group = self.device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("integrator_bind_group"),
            layout: &bind_group_layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: momenta_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: results_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: params_buffer.as_entire_binding(),
                },
            ],
        });

        // -----------------------------------------------------------------
        // Step 5: Dispatch compute shader
        // -----------------------------------------------------------------
        let workgroup_size = 64u32;
        let num_workgroups = ((n_valid as u32) + workgroup_size - 1) / workgroup_size;

        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("integrator_encoder"),
            });

        {
            let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: Some("integrator_pass"),
                timestamp_writes: None,
            });
            pass.set_pipeline(&pipeline);
            pass.set_bind_group(0, &bind_group, &[]);
            pass.dispatch_workgroups(num_workgroups, 1, 1);
        }

        // Copy results to staging buffer for CPU readback.
        encoder.copy_buffer_to_buffer(
            &results_buffer,
            0,
            &staging_buffer,
            0,
            (n_valid * std::mem::size_of::<f32>()) as u64,
        );

        self.queue.submit(std::iter::once(encoder.finish()));

        // -----------------------------------------------------------------
        // Step 6: Read back results
        // -----------------------------------------------------------------
        let results_f32 = pollster::block_on(self.read_buffer(&staging_buffer, n_valid));

        // -----------------------------------------------------------------
        // Step 7: Statistical reduction  (CPU)
        // -----------------------------------------------------------------
        // σ = (1 / 2s) · (1/N) · Σ |M|² · w_i
        //
        // The LIPS weight is already included in the phase-space point.
        let s = cms_energy * cms_energy;
        let flux = 2.0 * s;

        let mut sum = 0.0_f64;
        let mut sum_sq = 0.0_f64;

        for (i, &msq) in results_f32.iter().enumerate() {
            let weight = ps_points[i].weight;
            let f = (msq as f64) * weight;
            sum += f;
            sum_sq += f * f;
        }

        let n = n_valid as f64;
        let mean = sum / n;
        let variance = (sum_sq / n - mean * mean).max(0.0);
        let error = (variance / n).sqrt() / flux;
        let value = mean / flux;

        Ok(IntegrationResult {
            value,
            error,
            events_evaluated: n_valid,
            efficiency: n_valid as f64 / num_events as f64,
            relative_error: if value.abs() > 1e-30 {
                error / value.abs()
            } else {
                0.0
            },
        })
    }

    /// Read back an f32 buffer from the GPU (blocking).
    async fn read_buffer(&self, staging: &wgpu::Buffer, count: usize) -> Vec<f32> {
        let slice = staging.slice(..);
        let (tx, rx) = std::sync::mpsc::channel();

        slice.map_async(wgpu::MapMode::Read, move |result| {
            tx.send(result).expect("channel send");
        });

        self.device.poll(wgpu::Maintain::Wait);
        rx.recv()
            .expect("channel recv")
            .expect("buffer map failed");

        let data = slice.get_mapped_range();
        let results: Vec<f32> = bytemuck::cast_slice(&data).to_vec();
        drop(data);
        staging.unmap();

        results[..count].to_vec()
    }

    /// Query the GPU adapter name and backend for diagnostics.
    pub fn device_info(&self) -> &str {
        &self.adapter_info
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gpu_params_is_pod() {
        // Ensure GpuParams can be safely cast to/from bytes.
        let params = GpuParams {
            n_events: 1024,
            _pad: [0; 3],
        };
        let bytes: &[u8] = bytemuck::bytes_of(&params);
        assert_eq!(bytes.len(), 16);
    }

    // Integration tests requiring a GPU adapter are only run when
    // hardware is available.  These are gated behind `#[ignore]` to
    // avoid CI failures on headless machines.
    #[test]
    #[ignore]
    fn gpu_integrator_creates_successfully() {
        let integrator = GpuIntegrator::new();
        assert!(
            integrator.is_some(),
            "No GPU adapter found - this test requires a GPU"
        );
        if let Some(gpu) = integrator {
            eprintln!("GPU adapter: {}", gpu.device_info());
        }
    }
}
